# permissions for end users to administrate deceptionalertsinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: koney
    app.kubernetes.io/managed-by: kustomize
  name: deceptionpolicy-admin-role
rules:
- apiGroups:
  - research.dynatrace.com
  resources:
  - deceptionpolicies
  verbs:
  - '*'
- apiGroups:
  - research.dynatrace.com
  resources:
  - deceptionpolicies/status
  verbs:
  - get
