name: Build

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - v*

env:
  IMAGE_TAG_BASE: ghcr.io/dynatrace-oss/koney
  CONTROLLER_IMAGE: ghcr.io/dynatrace-oss/koney-controller
  ALERT_FORWARDER_IMAGE: ghcr.io/dynatrace-oss/koney-alert-forwarder

jobs:
  build-controller:
    name: Build controller
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.CONTROLLER_IMAGE }}
        flavor: |
          latest=auto
        tags: |
          type=sha
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      if: ${{ github.event_name == 'push' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name == 'push' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=${{ env.CONTROLLER_IMAGE }}:buildcache
        cache-to: ${{ github.event_name == 'push' && format('type=registry,ref={0}:buildcache,mode=max', env.CONTROLLER_IMAGE) || '' }}

  build-alert-forwarder:
    name: Build alert forwarder
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.ALERT_FORWARDER_IMAGE }}
        flavor: |
          latest=auto
        tags: |
          type=sha
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      if: ${{ github.event_name == 'push' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        context: ./alert-forwarder
        push: ${{ github.event_name == 'push' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=${{ env.ALERT_FORWARDER_IMAGE }}:buildcache
        cache-to: ${{ github.event_name == 'push' && format('type=registry,ref={0}:buildcache,mode=max', env.ALERT_FORWARDER_IMAGE) || '' }}

  push-chart:
    name: Push Helm chart
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - build-controller
    - build-alert-forwarder
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Package Helm chart
      run: VERSION=${GITHUB_REF_NAME#v} make helm-package

    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push Helm chart
      run: VERSION=${GITHUB_REF_NAME#v} make helm-push
