name: Test Helm Chart

on:
  pull_request:
  push:


jobs:
  test-chart:
    name: Install Helm chart
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Verify Kind installation
      run: kind version

    - name: Start cluster
      run: make setup-test-e2e

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Verify Helm installation
      run: helm version

    - name: Package Helm chart
      run: make helm-package

    - name: Build and push images
      run: |
        go mod tidy
        make docker-build docker-push

    - name: Install Helm chart
      run: |
        helm install test-koney-release ./dist/chart --create-namespace --namespace koney-system --wait --timeout 5m

    - name: Check Helm release status
      run: |
        helm status test-koney-release --namespace koney-system
