name: E2E Tests

on:
  pull_request:
  push:


jobs:
  test-e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Verify Kind installation
      run: kind version

    - name: Start cluster
      run: make setup-test-e2e

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Verify Helm installation
      run: helm version

    - name: Install Tetragon
      run: |
        helm repo add cilium https://helm.cilium.io
        helm repo update
        helm install tetragon cilium/tetragon -n kube-system --set dnsPolicy=ClusterFirstWithHostNet
        kubectl rollout status -n kube-system ds/tetragon -w --timeout=5m

    - name: Install Kive
      run: |
        kubectl apply -f https://raw.githubusercontent.com/San7o/kivebpf/refs/heads/main/dist/install-remote.yaml
        kubectl set image -n kivebpf-system daemonset kivebpf-manager "*=ghcr.io/san7o/kivebpf:dev"
        kubectl rollout status -n kivebpf-system ds/kivebpf-manager -w --timeout=5m

    - name: Run end-to-end tests
      run: |
        go mod tidy
        make test-e2e
